---
- name: Configure Apache with PHP
  hosts: webservers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Enable and start httpd
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Install PHP
    yum:
      name: php
      state: present

  - name: Install php-mysqlnd
    yum:
      name: php-mysqlnd
      state: present