---
- hosts: 192.168.169.137
  remote_user: root
  vars:
    - role: MASTER
    - priority: 255

  tasks:
    - name: Upload configuration to Nginx
      template:
        src: /root/myrole/templates/lvs_keepalived_conf.j2
        dest: /etc/keepalived/keepalived.conf

    - name: Restart keepalived service
      service:
        name: keepalived
        state: restarted
        enabled: yes

- hosts: 192.168.169.138
  remote_user: root
  vars:
    - role: BACKUP
    - priority: 200

  tasks:
    - name: Upload configuration to Nginx
      template:
        src: /root/myrole/templates/lvs_keepalived_conf.j2
        dest: /etc/keepalived/keepalived.conf

    - name: Restart keepalived service
      service:
        name: keepalived
        state: restarted
        enabled: yes